// <auto-generated />
using System;
using FZ.Auth.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FZ.WebAPI.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20250907152239_AuthV5")]
    partial class AuthV5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FZ.Auth.Domain.MFA.AuthAuditLog", b =>
                {
                    b.Property<int>("auditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("auditID"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userID")
                        .HasColumnType("int");

                    b.HasKey("auditID");

                    b.HasIndex("userID");

                    b.ToTable("AuthAuditLog", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.MFA.AuthMfaSecret", b =>
                {
                    b.Property<int>("mfaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mfaID"));

                    b.Property<bool>("isEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("recoveryCodes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("mfaID");

                    b.HasIndex("userID")
                        .IsUnique();

                    b.ToTable("AuthMfaSecret", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.MFA.AuthUserSession", b =>
                {
                    b.Property<int>("sessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sessionID"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("lastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("sessionID");

                    b.HasIndex("userID");

                    b.ToTable("AuthUserSession", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Role.AuthPermission", b =>
                {
                    b.Property<int>("permissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permissionID"));

                    b.Property<string>("permissionDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("permissionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("permissionID");

                    b.ToTable("AuthPermission", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Role.AuthRole", b =>
                {
                    b.Property<int>("roleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleID"));

                    b.Property<bool>("isDefault")
                        .HasColumnType("bit");

                    b.Property<string>("roleDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("roleID");

                    b.ToTable("AuthRole", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Role.AuthRolePermission", b =>
                {
                    b.Property<int>("rolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rolePermissionID"));

                    b.Property<int>("permissionID")
                        .HasColumnType("int");

                    b.Property<int>("roleID")
                        .HasColumnType("int");

                    b.HasKey("rolePermissionID");

                    b.HasIndex("permissionID");

                    b.HasIndex("roleID");

                    b.ToTable("AuthRolePermission", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Role.AuthUserRole", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("roleID")
                        .HasColumnType("int");

                    b.HasKey("userID");

                    b.HasIndex("roleID");

                    b.ToTable("AuthUserRole", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Token.AuthEmailVerification", b =>
                {
                    b.Property<int>("emailVerificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emailVerificationID"));

                    b.Property<string>("codeHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("consumedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("emailVerificationID");

                    b.HasIndex("userID");

                    b.ToTable("AuthEmailVerification", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Token.AuthPasswordReset", b =>
                {
                    b.Property<int>("passwordResetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("passwordResetID"));

                    b.Property<string>("codeHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("consumedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("passwordResetID");

                    b.HasIndex("userID");

                    b.ToTable("AuthPasswordReset", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Token.AuthRefreshToken", b =>
                {
                    b.Property<int>("refreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("refreshTokenID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sessionID")
                        .HasColumnType("int");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("refreshTokenID");

                    b.HasIndex("sessionID");

                    b.HasIndex("userID");

                    b.ToTable("AuthRefreshToken", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.User.AuthProfile", b =>
                {
                    b.Property<int>("profileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("profileID"));

                    b.Property<string>("avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("profileID");

                    b.HasIndex("userID")
                        .IsUnique();

                    b.ToTable("AuthProfile", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.User.AuthUser", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userID"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("googleSub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("tokenVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("userID");

                    b.ToTable("AuthUser", "auth");
                });

            modelBuilder.Entity("FZ.Auth.Domain.MFA.AuthAuditLog", b =>
                {
                    b.HasOne("FZ.Auth.Domain.User.AuthUser", "user")
                        .WithMany("auditLogs")
                        .HasForeignKey("userID");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FZ.Auth.Domain.MFA.AuthMfaSecret", b =>
                {
                    b.HasOne("FZ.Auth.Domain.User.AuthUser", "user")
                        .WithOne("mfaSecret")
                        .HasForeignKey("FZ.Auth.Domain.MFA.AuthMfaSecret", "userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("FZ.Auth.Domain.MFA.AuthUserSession", b =>
                {
                    b.HasOne("FZ.Auth.Domain.User.AuthUser", "user")
                        .WithMany("sessions")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Role.AuthRolePermission", b =>
                {
                    b.HasOne("FZ.Auth.Domain.Role.AuthPermission", "permission")
                        .WithMany("rolePermissions")
                        .HasForeignKey("permissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FZ.Auth.Domain.Role.AuthRole", "role")
                        .WithMany("rolePermissions")
                        .HasForeignKey("roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Role.AuthUserRole", b =>
                {
                    b.HasOne("FZ.Auth.Domain.Role.AuthRole", "role")
                        .WithMany("userRoles")
                        .HasForeignKey("roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FZ.Auth.Domain.User.AuthUser", "user")
                        .WithMany("userRoles")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Token.AuthEmailVerification", b =>
                {
                    b.HasOne("FZ.Auth.Domain.User.AuthUser", "user")
                        .WithMany("emailVerifications")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Token.AuthPasswordReset", b =>
                {
                    b.HasOne("FZ.Auth.Domain.User.AuthUser", "user")
                        .WithMany("passwordResets")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Token.AuthRefreshToken", b =>
                {
                    b.HasOne("FZ.Auth.Domain.MFA.AuthUserSession", "session")
                        .WithMany("refreshTokens")
                        .HasForeignKey("sessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FZ.Auth.Domain.User.AuthUser", "user")
                        .WithMany("refreshTokens")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("session");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FZ.Auth.Domain.User.AuthProfile", b =>
                {
                    b.HasOne("FZ.Auth.Domain.User.AuthUser", "user")
                        .WithOne("profile")
                        .HasForeignKey("FZ.Auth.Domain.User.AuthProfile", "userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("FZ.Auth.Domain.MFA.AuthUserSession", b =>
                {
                    b.Navigation("refreshTokens");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Role.AuthPermission", b =>
                {
                    b.Navigation("rolePermissions");
                });

            modelBuilder.Entity("FZ.Auth.Domain.Role.AuthRole", b =>
                {
                    b.Navigation("rolePermissions");

                    b.Navigation("userRoles");
                });

            modelBuilder.Entity("FZ.Auth.Domain.User.AuthUser", b =>
                {
                    b.Navigation("auditLogs");

                    b.Navigation("emailVerifications");

                    b.Navigation("mfaSecret")
                        .IsRequired();

                    b.Navigation("passwordResets");

                    b.Navigation("profile")
                        .IsRequired();

                    b.Navigation("refreshTokens");

                    b.Navigation("sessions");

                    b.Navigation("userRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
