app = "filmzone-api"
primary_region = "sin"

[build]
  # không bắt buộc ghi image ở đây vì workflow đã dùng --image override
  # image = "DOCKERHUB_USER/filmzone-api:latest"

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
