app = "filmzone-api"
primary_region = "sin"

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 8080
  force_https = true        # TLS ở Fly edge (container vẫn HTTP)
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[env]
  ASPNETCORE_URLS = "http://+:8080"
