name: api-ci

on:
  push:
    branches: [ main ]          # đổi nếu bạn dùng nhánh khác
    paths:
      - 'FZ.WebAPI/**'
      - '.github/workflows/api-ci.yml'
  workflow_dispatch: {}          # cho phép chạy tay khi cần

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/filmzone-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: FZ.WebAPI                 # <<< QUAN TRỌNG
          file: FZ.WebAPI/Dockerfile         # <<< QUAN TRỌNG
          push: true
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:latest
            docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io (dùng image vừa build)
        run: |
          flyctl deploy \
            --app filmzone-api \
            --image docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
