name: Build & Push API + Deploy Fly

on:
  push:
    branches: [ "master" ]   # đổi "main" nếu cần
  workflow_dispatch:

env:
  IMAGE_NAME: emyeuaidayy/filmzone-api   # sửa đúng namespace/repo Docker Hub của bạn

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: FZ.WebAPI/FilmZone/Dockerfile
          push: true
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:latest
            docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        if: success()
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy \
            -a filmzone-api \
            --image docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --remote-only
