name: Build & Deploy to Koyeb

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: docker.io/emyeuaidayy/filmzone-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: FZ.WebAPI
          file: FZ.WebAPI/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      # >>> CÀI Koyeb CLI (có sudo) <<<
      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://get.koyeb.com/install.sh | sudo bash
          which koyeb
          koyeb --version

      - name: Login to Koyeb
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
        run: koyeb login --access-token "$KOYEB_TOKEN"

      # Cập nhật service dùng image mới; nếu update không hỗ trợ, fallback redeploy
      - name: Update Koyeb service image
        env:
          KOYEB_SERVICE: ${{ secrets.KOYEB_SERVICE }}   # ví dụ: filmzone-api hoặc app-name/service-name
        run: |
          koyeb services update "$KOYEB_SERVICE" \
            --image "${{ env.IMAGE_NAME }}:${{ github.sha }}" || \
          koyeb services redeploy "$KOYEB_SERVICE"
