name: Build & Deploy to Koyeb

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: docker.io/emyeuaidayy/filmzone-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: FZ.WebAPI
          file: FZ.WebAPI/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      # ---- Install Koyeb CLI (không dùng get.koyeb.com) ----
      - name: Install Koyeb CLI (from GitHub Releases)
        run: |
          set -euo pipefail
          TMP="$(mktemp -d)"
          # tải binary linux-amd64; nếu bạn dùng runner kiến trúc khác, đổi tên file tương ứng
          curl -fsSL -o "$TMP/koyeb.tar.gz" \
            https://github.com/koyeb/koyeb-cli/releases/latest/download/koyeb-linux-amd64.tar.gz
          sudo tar -xzf "$TMP/koyeb.tar.gz" -C /usr/local/bin koyeb
          koyeb --version

      - name: Login to Koyeb
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
        run: koyeb login --access-token "$KOYEB_TOKEN"

      - name: Update Koyeb service image
        env:
          KOYEB_SERVICE: ${{ secrets.KOYEB_SERVICE }}   # ví dụ: filmzone-api
        run: |
          # cập nhật image theo sha; nếu update không hỗ trợ, fallback redeploy
          koyeb services update "$KOYEB_SERVICE" \
            --image "${{ env.IMAGE_NAME }}:${{ github.sha }}" || \
          koyeb services redeploy "$KOYEB_SERVICE"
