name: Build & Deploy to Koyeb

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: filmzone-koyeb
  cancel-in-progress: true

env:
  IMAGE_NAME: emyeuaidayy/filmzone-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KOYEB_APP: ${{ secrets.KOYEB_APP }}
      KOYEB_SERVICE: ${{ secrets.KOYEB_SERVICE }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: FZ.WebAPI
          file: FZ.WebAPI/Dockerfile
          push: true
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:latest
            docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # Cài & cấu hình Koyeb CLI
      - name: Install Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_TOKEN }}

      # (Tuỳ chọn) Kiểm tra app/service có tồn tại
      # - run: |
      #     koyeb app list
      #     koyeb service list $KOYEB_APP

      # Redeploy service để Koyeb pull image :latest vừa push
      - name: Redeploy service on Koyeb
        run: koyeb service redeploy "$KOYEB_APP/$KOYEB_SERVICE"
