name: Build & Deploy to Koyeb
on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: emyeuaidayy/filmzone-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: FZ.WebAPI
          file: FZ.WebAPI/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

      # Install Koyeb CLI
      - name: Install Koyeb CLI
        run: curl -fsSL https://get.koyeb.com/install.sh | bash

      - name: Login Koyeb
        run: koyeb login --access-token "${{ secrets.KOYEB_TOKEN }}"

      # Cập nhật service dùng image mới (chọn một trong hai lệnh phù hợp)
      - name: Update service image
        run: |
          koyeb services update ${{ secrets.KOYEB_SERVICE }} \
            --image docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }} || \
          koyeb services redeploy ${{ secrets.KOYEB_SERVICE }}
